query SearchJournalRecords(
	$where: JournalWhereInput
	$orderBy: [JournalOrderByWithRelationInput!]
	$skip: Int
	$take: Int
	$cursor: JournalWhereUniqueInput
) {
	journals(
		where: $where
		orderBy: $orderBy
		skip: $skip
		take: $take
		cursor: $cursor
	) {
		...JournalEntryRecord
	}
}

query SearchJeLineRecords(
	$where: JournalEntryWhereInput
	$orderBy: [JournalEntryOrderByWithRelationInput!]
	$skip: Int
	$take: Int
	$cursor: JournalEntryWhereUniqueInput
) {
	journalEntries(
		where: $where
		orderBy: $orderBy
		skip: $skip
		take: $take
		cursor: $cursor
	) {
		...JournalEntryLedgerRecord
	}
}

# query GetJournalFormInputs($periodWhere: PeriodWhereInput) {
# 	periods(orderBy: [{ year: asc }, { month: asc }], where: $periodWhere) {
# 		...PeriodRecord
# 	}
# 	glAccounts(orderBy: [{ accountNumber: asc }]) {
# 		...GlAccInfo
# 	}
# 	entities(orderBy: [{ id: asc }]) {
# 		...EntityInfo
# 	}
# 	books(orderBy: [{ id: asc }]) {
# 		...BookLedgerInfo
# 	}
# }

query QueryJournalFormInputs($periodWhere: PeriodWhereInput) {
	periods(orderBy: [{ year: asc }, { month: asc }], where: $periodWhere) {
		...PeriodRecord
	}
	glAccounts(orderBy: [{ accountNumber: asc }]) {
		...GlAccInfo
	}
	entities(orderBy: [{ id: asc }]) {
		...EntityInfo
	}
	books(orderBy: [{ id: asc }]) {
		...BookLedgerInfo
	}
}
