query SearchJournalRecords(
	$where: JournalWhereInput
	$orderBy: [JournalOrderByWithRelationInput!]
	$skip: Int
	$take: Int
	$cursor: JournalWhereUniqueInput
) {
	journals(
		where: $where
		orderBy: $orderBy
		skip: $skip
		take: $take
		cursor: $cursor
	) {
		...JournalEntryRecord
	}
}

query SearchJeLineRecords(
	$where: JournalEntryWhereInput
	$orderBy: [JournalEntryOrderByWithRelationInput!]
	$skip: Int
	$take: Int
	$cursor: JournalEntryWhereUniqueInput
) {
	journalEntries(
		where: $where
		orderBy: $orderBy
		skip: $skip
		take: $take
		cursor: $cursor
	) {
		...JournalEntryLedgerRecord
	}
}
