query SearchTranScheduleRecords(
	$where: TranScheduleWhereInput
	$orderBy: [TranScheduleOrderByWithRelationInput!]
) {
	tranSchedules(where: $where, orderBy: $orderBy) {
		...TranScheduleRecord
	}
}
