#import "./fragments/tiller.gql"

query SearchTillerCatRecords(
	$where: TillerCategoryWhereInput
	$orderBy: [TillerCategoryOrderByWithRelationInput!]
) {
	tillerCategories(where: $where, orderBy: $orderBy) {
		...TillerCatRecord
	}
}

query SearchTillerAccRecords(
	$where: TillerAccountWhereInput
	$orderBy: [TillerAccountOrderByWithRelationInput!]
) {
	tillerAccounts(where: $where, orderBy: $orderBy) {
		...TillerAccountRecord
	}
}

query SearchBaseTillerTrans(
	$where: TillerTranWhereInput
	$orderBy: [TillerTranOrderByWithRelationInput!]
) {
	tillerTrans(where: $where, orderBy: $orderBy) {
		...BaseTillerTranInfo
	}
}

query SearchTillerTranRecords(
	$where: TillerTranWhereInput
	$orderBy: [TillerTranOrderByWithRelationInput!]
) {
	tillerTrans(where: $where, orderBy: $orderBy) {
		...TillerTranRecord
	}
}

query GetBaseTillerRecInfo(
	$catOrderBy: [TillerCategoryOrderByWithRelationInput!]
	$catWhere: TillerCategoryWhereInput
	$accOrderBy: [TillerAccountOrderByWithRelationInput!]
	$accWhere: TillerAccountWhereInput
	$tranOrderBy: [TillerTranOrderByWithRelationInput!]
	$tranWhere: TillerTranWhereInput
) {
	tillerCategories(where: $catWhere, orderBy: $catOrderBy) {
		...BaseTillerCatInfo
	}
	tillerAccounts(where: $accWhere, orderBy: $accOrderBy) {
		...BaseTillerAccInfo
	}
	tillerTrans(where: $tranWhere, orderBy: $tranOrderBy) {
		...BaseTillerTranInfo
	}
}

query TillerTranAggs($aggWhere: TillerTranWhereInput) {
	aggregateTillerTran(where: $aggWhere) {
		idCount
		tranIdCount
		minDate
		minDateAdded
		minCreatedAt
		maxDate
		maxDateAdded
		maxCreatedAt
		unRecCount
	}
}
