fragment JournalRecInfo on Journal {
	id
	tranNumber
	tranDate
}

fragment JournalHeaderDetail on Journal {
	id
	createdAt
	updatedAt
	tranNumber
	tranDate
	bookId
	book {
		...BookLedgerInfo
	}
	description
	tranSource
	reversalDate
	externalId
	createdFromTillerTranId
	idReversalOf
	postingMonth
	postingYear
	postingPeriod {
		id
		locked
		label
	}
	_count {
		entries
		migrationLoanChanges
		templateForTranSchedules
	}
}

fragment JournalPageRecord on Journal {
	...JournalHeaderDetail
	reversalOf {
		...JournalRecInfo
	}
	reversedTransaction {
		...JournalRecInfo
	}
	createdFromTillerTran {
		...BaseTillerTranInfo
	}
}
