fragment JournalRecInfo on Journal {
	id
	tranNumber
	tranDate
}

fragment JournalHeaderDetail on Journal {
	id
	createdAt
	updatedAt
	tranNumber
	tranDate
	bookId
	book {
		...BookLedgerInfo
	}
	description
	tranSource
	reversalDate
	externalId
	createdFromTillerTranId
	idReversalOf
	postingMonth
	postingYear
	postingPeriod {
		id
		locked
		label
	}
	_count {
		entries
		migrationLoanChanges
		templateForTranSchedules
	}
}

fragment JournalLineDetail on JournalEntry {
	journalId
	id
	createdAt
	updatedAt
	amount
	glAccountNumber
	isDebit
	entrySource
	entityId
	memo
	glAccount {
		...GlAccInfo
	}
}

fragment JournalPageRecord on Journal {
	...JournalHeaderDetail
	reversalOf {
		...JournalRecInfo
	}
	reversedTransaction {
		...JournalRecInfo
	}
	createdFromTillerTran {
		...BaseTillerTranInfo
	}
	entries {
		...JournalLineDetail
	}
}
