fragment EntityInfo on Entity {
	id
	name
	system
	entityType
	description
	defaultAccountNumber
}

fragment JournalEntryLineRecord on JournalEntry {
	id
	amount
	glAccountNumber
	isDebit
	entrySource
	entityId
	memo
	glAccount {
		...GlAccInfo
	}
}

fragment JournalHeaderInfo on Journal {
	id
	tranNumber
	tranDate
	bookId
	description
	tranSource
	reversalDate
	externalId
	createdFromTillerTranId
	idReversalOf
	postingPeriod {
		id
		locked
		label
	}
}
fragment JournalEntryHeaderRecord on Journal {
	...JournalHeaderInfo
	createdAt
	updatedAt
}

fragment JournalEntryRecord on Journal {
	...JournalEntryHeaderRecord
	entries {
		...JournalEntryLineRecord
	}
	_count {
		entries
		migrationLoanChanges
		templateForTranSchedules
	}
}

fragment JournalEntryLedgerRecord on JournalEntry {
	journalId
	...JournalEntryLineRecord
	journal {
		...JournalHeaderInfo
	}
	entity {
		...EntityInfo
	}
}
