fragment TranScheduleRecord on TranSchedule {
	id
	createdAt
	updatedAt
	name
	dayOfMonth
	dayOfWeek
	frequency
	interval
	isActive
	startDate
	endDate
	templateJournalId
	templateJournal {
		bookId
		id
		tranNumber
		tranDate
	}
	_count {
		scheduleLogs
	}
}

fragment TranSchedResultInfo on TranScheduleResultModel {
	id
	name
	_count {
		scheduleLogs
	}
}
