fragment BaseTillerCatInfo on TillerCategory {
	id
	name
	type
	group
	glAccountNumber
	_count {
		tillerTrans
	}
}

fragment TillerCatRecord on TillerCategory {
	id
	createdAt
	updatedAt
	name
	type
	group
	glAccountNumber
	_count {
		tillerTrans
	}
	glAccount {
		...GlAccInfo
	}
}

fragment BaseTillerAccInfo on TillerAccount {
	id
	name
	group
	institution
	glAccountNumber
	_count {
		tillerTrans
	}
}

fragment TillerAccountRecord on TillerAccount {
	id
	createdAt
	updatedAt
	name
	accountId
	glAccountNumber
	group
	institution
	_count {
		tillerTrans
	}
	glAccount {
		...GlAccInfo
	}
}

fragment BaseTillerTranInfo on TillerTran {
	id
	date
	dateAdded
	account
	category
	amount
	reconciled
	excluded
	generatedJournal {
		id
		tranNumber
	}
}

fragment TillerTranRecord on TillerTran {
	id
	createdAt
	updatedAt
	date
	dateAdded
	description #  no
	reconciled
	transactionId #  no
	excluded
	category
	amount
	account
	generatedJournal {
		id
		tranNumber
	}
}
