/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PInputNumber: typeof import('primevue/inputnumber')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
