/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PCheckbox: typeof import('primevue/checkbox')['default']
    PColumn: typeof import('primevue/column')['default']
    PConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDatePicker: typeof import('primevue/datepicker')['default']
    PInputNumber: typeof import('primevue/inputnumber')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMultiSelect: typeof import('primevue/multiselect')['default']
    PPickList: typeof import('primevue/picklist')['default']
    PProgressSpinner: typeof import('primevue/progressspinner')['default']
    PSelect: typeof import('primevue/select')['default']
    PStep: typeof import('primevue/step')['default']
    PStepList: typeof import('primevue/steplist')['default']
    PStepper: typeof import('primevue/stepper')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
